
name: "Continuous Integration"

on:
  pull_request:

jobs:
  static-analysis-psalm:
    name: Static Analysis with Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@1.8.1"
        with:
          coverage: "none"
          php-version: "7.4"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1.0.3"
        with:
          path: "~/.composer/cache"
          key: "composer-${{ hashFiles('composer.json') }}"
          restore-keys: "composer-"

      - name: "Install dependencies with composer"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: Psalm
        run: "vendor/bin/psalm"
